export const bd_cards_formacao = [
    { titulo: "Smartphone Samsung Galaxy S23", preco: "R$ 4.999,00" },
    { titulo: "Notebook Dell Inspiron 15", preco: "R$ 3.499,00" },
    { titulo: "Fones de Ouvido JBL T500", preco: "R$ 179,00" },
    { titulo: "Smartwatch Apple Watch Series 8", preco: "R$ 3.999,00" },
    { titulo: "Câmera Digital Canon EOS 90D", preco: "R$ 8.999,00" },
    { titulo: "TV LED 55\" Samsung QLED", preco: "R$ 4.699,00" },
    { titulo: "Micro-ondas Panasonic 20L", preco: "R$ 399,00" },
    { titulo: "Aspirador de Pó Philco 1600W", preco: "R$ 299,00" },
    { titulo: "Cadeira Gamer Corsair T3 Rush", preco: "R$ 1.799,00" },
    { titulo: "Processador Intel Core i7-12700K", preco: "R$ 2.299,00" },
    { titulo: "Teclado Mecânico Razer Huntsman Mini", preco: "R$ 1.099,00" },
    { titulo: "Cafeteira Expresso Nespresso Essenza Mini", preco: "R$ 549,00" },
    { titulo: "Console PlayStation 5", preco: "R$ 4.499,00" },
    { titulo: "Game Control Xbox Elite Series 2", preco: "R$ 1.099,00" },
    { titulo: "Airfryer Philips Walita 3L", preco: "R$ 649,00" },
    { titulo: "Kindle Paperwhite 8GB", preco: "R$ 599,00" },
    { titulo: "Câmera de Segurança Nest Cam", preco: "R$ 1.299,00" },
    { titulo: "Laptop HP Pavilion 14", preco: "R$ 2.699,00" },
    { titulo: "Máquina de Lavar Samsung 11kg", preco: "R$ 2.299,00" },
    { titulo: "Secador de Cabelo Taiff Gama", preco: "R$ 189,00" },
    { titulo: "Relógio Casio G-Shock", preco: "R$ 499,00" },
    { titulo: "AirPods Pro 2ª Geração", preco: "R$ 2.099,00" },
    { titulo: "Mochila para Notebook Samsonite", preco: "R$ 299,00" },
    { titulo: "Câmera Instantânea Fujifilm Instax Mini 11", preco: "R$ 499,00" },
    { titulo: "Churrasqueira Elétrica Britânia 2000W", preco: "R$ 239,00" },
    { titulo: "Óculos de Sol Ray-Ban Aviator", preco: "R$ 899,00" }
];